name: Create/Update THIRD-PARTY-LICENSE-ACKNOWLEDGEMENTS.json

on:
    push:
    pull_request:
        types:
            - ready_for_review

jobs:
    create-third-party-license-acknowledgments:
        timeout-minutes: 5
        runs-on: ubuntu-latest
        permissions:
            contents: write
        outputs:
            commit: ${{ steps.create-commit.outputs.commit }}
        steps:
            - name: Check out code
              uses: actions/checkout@v3
            - name: Initialize git config
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email noreply@github.com
            - name: Setup project
              run: npm run setup
            - name: Create THIRD-PARTY-LICENSE-ACKNOWLEDGEMENTS.json (will overwrite)
              run: npm run third-party-license:generate
            - name: Commit and push updated version (if it exists)
              run: |
                  git diff --exit-code -- frontend/src/assets/source-code/THIRD-PARTY-LICENSE-ACKNOWLEDGEMENTS.json ||
                  (git add frontend/src/assets/source-code/THIRD-PARTY-LICENSE-ACKNOWLEDGEMENTS.json &
                  git commit --signoff --message "update-third-party-license-acknowledgments" &
                  echo "commit=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT" &
                  git push)
