name: Update THIRD-PARTY-LICENSE-ACKNOWLEDGEMENTS.json

on:
    push:
    pull_request:
        types:
            - ready_for_review

jobs:
    update-third-party-license-acknowledgments:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        outputs:
            commit: ${{ steps.create-commit.outputs.commit }}
        steps:
            - name: Check out code
              uses: actions/checkout@v3
            - name: Initialize git config
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email noreply@github.com
            - name: Cache node modules
              uses: ./.github/actions/cache-build
              with:
                  shared-dist: 'false'
            - name: Create THIRD-PARTY-LICENSE-ACKNOWLEDGEMENTS.json
              run: npm run third-party-license:generate
            - name: Commit updated version and changelog
              id: create-commit
              run: |
                  git add frontend/src/assets/about/THIRD-PARTY-LICENSE-ACKNOWLEDGEMENTS.json
                  git commit --message "update-third-party-license-acknowledgments"
                  echo "commit=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
            - name: Push THIRD-PARTY-LICENSE-ACKNOWLEDGEMENTS.json
              run: git push
